### ISSUE TITLE
List block - problem after selecting list over image block

### ISSUE THREAD

**Issue by dziudek** [dziudek/publii-block-editor#63]
1. Add empty image block
2. Select list block over the added image block
3. Cursor goes to the "Enter a caption" field in the newly added empty image block

**Comment by dziudek** [comment]
@bobmitro - I am unable to reproduce this issue - can you provide some example via video?

**Comment by bobmitro** [comment]
Have a look at the attached video.

[video.zip](https://github.com/dziudek/publii-block-editor/files/3572794/video.zip)
